<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Wed Oct 23 2024 16:29:50 GMT+0200 (Mitteleuropäische Sommerzeit)). */
return array(
	'src/public/dist/admin.js' => 'a6641c497fc6fc558e8d67a1b7eb023c',
	'src/public/dist/frontend.js' => 'd032b379da7cfb1d0a824f2322d9acbe',
	'src/public/dist/index.js' => '3cb9f0bab73a63db0af5b221d05adf83',
	'src/public/dist/vendor-admin.js' => '902cb669c250eb53a78087d385b77613',
	'src/public/dist/vendor-frontend.js' => 'd76f382bbc11b86a850091759b6f32c2',
	'src/public/dist/admin.css' => '7b5715e10f2158c5e78ae83e24fdf33d',
	'src/public/dist/frontend.css' => 'e7910e599a913fcde0796f14ec03e6aa',
	'src/public/dev/0.js' => 'fcc7956beef7cec7eb14274da98a4f93',
	'src/public/dev/1.js' => '29705f5b0c80680e50800e2b67264809',
	'src/public/dev/admin.js' => '9dd126e8649c896e1ab0383d557bb53c',
	'src/public/dev/frontend.js' => 'd9f2ff6994070ca88f3d32d8338cc0fb',
	'src/public/dev/i18n-dir/0.js' => 'fcc7956beef7cec7eb14274da98a4f93',
	'src/public/dev/i18n-dir/1.js' => '29705f5b0c80680e50800e2b67264809',
	'src/public/dev/i18n-dir/admin.js' => '889c7f99afc8fea97ed6b0f98baf29a2',
	'src/public/dev/i18n-dir/frontend.js' => 'c53b49752ec9234bf5c07710c421ff3a',
	'src/public/dev/vendor-admin.js' => '1615d0301a984d79884b0d17e7aac31b',
	'src/public/dev/vendor-frontend.js' => '8c1a8b1562ee24a7d3c428f9aea7f846',
	'src/public/dev/admin.css' => '579a4fd4b262a7b35cf73583b33d3a91',
	'src/public/dev/frontend.css' => '7ed47d05b50e9948d7b746a7624a0c68',
);
